# Generated by Django 5.0.6 on 2024-05-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_schedule_alter_calendar_therapist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='schedule',
            field=models.PositiveSmallIntegerField(choices=[(7, '07:00'), (23, '23:00'), (15, '15:00'), (21, '21:00'), (13, '13:00'), (4, '04:00'), (9, '09:00'), (10, '10:00'), (19, '19:00'), (17, '17:00'), (22, '22:00'), (8, '08:00'), (16, '16:00'), (14, '14:00'), (20, '20:00'), (6, '06:00'), (11, '11:00'), (5, '05:00'), (12, '12:00'), (18, '18:00')]),
        ),
    ]
