# Generated by Django 5.0.6 on 2024-05-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_calendar_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['week_day']},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='schedule',
            field=models.PositiveSmallIntegerField(choices=[(6, '06:00'), (17, '17:00'), (20, '20:00'), (21, '21:00'), (4, '04:00'), (13, '13:00'), (23, '23:00'), (8, '08:00'), (14, '14:00'), (7, '07:00'), (16, '16:00'), (5, '05:00'), (12, '12:00'), (10, '10:00'), (22, '22:00'), (15, '15:00'), (18, '18:00'), (11, '11:00'), (19, '19:00'), (9, '09:00')]),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='week_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
    ]
