# Generated by Django 5.0.6 on 2024-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_alter_calendar_options_calendar_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
