# Generated by Django 5.0.6 on 2024-05-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_city_alter_profile_uf_and_more'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatments', to='accounts.profile'),
        ),
    ]
