# Generated by Django 5.0.6 on 2024-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_alter_treatment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
