# Generated by Django 5.0.6 on 2024-05-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0006_alter_calendar_is_active'),
        ('treatments', '0003_alter_treatment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='calendars.calendar'),
        ),
    ]
