# Generated by Django 5.0.6 on 2024-05-13 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibge_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('complaint', models.TextField()),
                ('psychiatric', models.BooleanField()),
                ('emergency_number', models.CharField(max_length=20)),
                ('crp', models.CharField(blank=True, max_length=20, null=True)),
                ('platform', models.CharField(blank=True, choices=[('Whatsapp', 'Whatsapp'), ('Zoom', 'Zoom'), ('Google Meets', 'Google Meets'), ('Facetime', 'Facetime'), ('Microsoft Teams', 'Microsoft Teams'), ('Jitsi', 'Jitsi'), ('Outro', 'Outro')], max_length=50, null=True)),
                ('crp_check', models.BooleanField()),
                ('trained', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ibge_data.city')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='ibge_data.uf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
