# Generated by Django 5.0.6 on 2024-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_city_alter_profile_uf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='e_psi',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
