# Generated by Django 5.0.6 on 2024-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_e_psi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='crp_check',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='e_psi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='psychiatric',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trained',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], null=True),
        ),
    ]
