# Generated by Django 5.0.6 on 2024-05-17 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_profile_city_alter_profile_uf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAgreementVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsageAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('acceptance', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usageagreements', to='usage_agreement.usageagreementversion')),
            ],
        ),
    ]
